name: PR Build

on: pull_request

permissions:
  contents: read

concurrency:
  group: "pr-build-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Assemble Quartz
        run: ./scripts/assemble.sh

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npx quartz build

      - name: Search quality
        uses: SilesianSolutions/search-quality-kit@v0
